server:
  port: 8080
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://192.168.103.163:3306/smartcloud_anacenter?characterEncoding=utf8&useSSL=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.ajin.springdemo.model
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl